// Preamble generated by CrankLang
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <ctime>
#include <string>
#include <vector>
int  function_without_definition(int  x);
int  function_without_definition(int  x)
;
